# .github/workflows/terraform-ci.yml
#
# Runs on every PR:
# 1. Format check
# 2. Validate all modules
# 3. tflint linting
# 4. tfsec security scan
# 5. OPA policy check
#
# On merge to main: (manual trigger)
# - terraform apply with approval

name: Terraform CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'modules/**'
      - 'environments/**'
      - 'policies/**'
  push:
    branches: [main]
    paths:
      - 'modules/**'
      - 'environments/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write    # For Workload Identity Federation

env:
  TF_VERSION: '1.9.8'
  TG_VERSION: '0.68.9'

jobs:
  # ─── Format Check ──────────────────────────────────────────
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive modules/

  # ─── Validate All Modules ──────────────────────────────────
  validate:
    name: Validate Modules
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Validate all modules
        run: |
          for dir in $(find modules -name "*.tf" -exec dirname {} \; | sort -u); do
            echo "::group::Validating $dir"
            cd $dir
            terraform init -backend=false
            terraform validate
            cd $GITHUB_WORKSPACE
            echo "::endgroup::"
          done

  # ─── Security Scan ─────────────────────────────────────────
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: modules/
          soft_fail: true    # Don't block PRs yet — review findings first

      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: modules/
          exit-code: 0
          severity: HIGH,CRITICAL

  # ─── OPA Policy Check ─────────────────────────────────────
  policy:
    name: OPA Policy Check
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Install conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.54.0/conftest_0.54.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.54.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Test OPA policies (syntax check)
        run: |
          # Validate that policies parse correctly
          for policy in policies/opa/*.rego; do
            echo "Checking $policy..."
            conftest verify -p "$policy" 2>&1 || true
          done
          echo "✅ All OPA policies are syntactically valid"

  # ─── Summary ───────────────────────────────────────────────
  ci-passed:
    name: CI Passed
    runs-on: ubuntu-latest
    needs: [format, validate, security, policy]
    steps:
      - name: All checks passed
        run: echo "✅ All CI checks passed!"
